select
snapshot_date,
total_remain_principal,
un_settle_num,
weight_avg_inter_rate,
weight_remain_term,
current_repay_amount,
current_early_settle_amount,
current_back_amount,
accum_90to_amount,
overdue30_amount_rate,
static_90to_amount_rate
from dm_eagle.report_ht_asset_project
where snapshot_date=$snapshot_date$;
