spring:
    thymeleaf:
        cache: false
    messages:
        basename: i18n
    mvc:
        hiddenmethod:
            filter:
                enabled: true
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.18.100:33061/java_web?useUnicode=true&characterEncoding=utf-8
        username: root
        password: '000000'
        type: com.alibaba.druid.pool.DruidDataSource
        initialization-mode: always
        schema:
            - classpath:sql/employee.sql
            - classpath:sql/department.sql

        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall
        maxPoolPreparedStatementPerConnectionSize: 20
        useGlobalDataSourceStat: true
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/mapper/*.xml
